name: CI

on: [push]

jobs:
  contracts:
    name: Test Create2 Deployer
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["10.x", "12.x", "14.x"]

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: yarn install

      - name: Test Deployer
        run: yarn run test
